apiVersion: v1
kind: ServiceAccount
metadata:
  name: nkml
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nkml
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - patch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nkml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nkml
subjects:
  - kind: ServiceAccount
    name: nkml
    namespace: default
---
kind: DaemonSet
apiVersion: apps/v1
metadata: 
  name: nkml
  labels:
    app.kubernetes.io/name: nkml
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nkml
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nkml
    spec:
      serviceAccountName: nkml
      containers:
      - name: nkml
        image: leonnicolas/nkml
        args: 
        - --hostname=$(NODE_NAME)
        - --label-mod=wireguard
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: http
          containerPort: 8080
