name: build

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ 'amd64', 'arm', 'arm64' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build ${{ matrix.arch }}
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - run: GO_ARCH=${{ matrix.arch }} go build
