name: build

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ 'amd64', 'arm', 'arm64' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ${{ matrix.arch }}
        uses: actions/setup-go@v2
        with:
         go-version: '1.17'
      - run: GO_ARCH=${{ matrix.arch }} go build
