name: test

on:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - run: docker build -t "nkml:e2e" .
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go test .
